export const supportQuotesSavage = [
  "We tried nothing. Just kidding.",
  "It’s broken in a new way.",
  "Yes, we read the ticket.",
  "That was working yesterday.",
  "Computers remember everything.",
  "Support: calmly panicking inside.",
  "That’s… not supposed to happen.",
  "You found the one bug.",
  "It’s always user timing.",
  "Support runs on optimism.",
  "We fixed it accidentally.",
  "Please stop clicking randomly.",
  "That’s not how software works.",
  "Support: explaining buttons daily.",
  "We swear it passed testing.",
  "It’s thinking. Please wait.",
  "That error looks familiar.",
  "Support: professional guessers.",
  "The bug moved locations.",
  "Yes, it’s supposed to load.",
  "Support: managing expectations gently.",
  "We blame the update.",
  "Have you tried patience?",
  "Support: where logic goes softly.",
  "It works… eventually.",
  "That’s a known surprise.",
  "Support fixes what hope can’t.",
  "We didn’t break it.",
  "That feature is adventurous.",
  "Support: translating chaos politely.",
  "It’s not frozen. It’s thinking.",
  "You clicked it twice.",
  "Support: solving mysteries hourly.",
  "That’s technically expected behavior.",
  "We tested this. Honestly.",
  "Support: keeping calm publicly.",
  "The system needs encouragement.",
  "That issue chose today.",
  "Support: one reboot away.",
  "It’s loading emotionally.",
  "That button felt threatened.",
  "Support survives release day.",
  "This ticket escalated itself.",
  "Support: smiling through logs.",
  "The fix was obvious later.",
  "Support: because humans exist.",
  "That worked after lunch.",
  "Support: professionally confused.",
  "The bug was shy.",
  "Support never sleeps. Mostly."
];
